### ISSUE TITLE
[Help] Save all tunings

### ISSUE THREAD

**Issue by SirOficial** [LeoSHK/vrp_lscustom#1]
Boa tarde, eu tuno o veículo, as modificações na Ls Custom ficam salvas, porém quando spawno o carro pela garagem não volta com todas as modificações que eu fiz, por exemplo, motor, transmissão, vidro, entre alguns outros. Mas quando eu entro na Ls Custom, está lá as modificações que fiz salva, porém só não spawna mesmo com as modificações o carro. Modificações como cor, neon, bumpers e etc estão sendo salvas sim. Como posso resolver isso?

Good afternoon, I have the vehicle, the modifications in Ls Custom are saved, but when I spawn the car through the garage does not come back with all the modifications I made, for example, engine, transmission, glass, among some others. But when I enter the Ls Custom, there are the modifications I did save, but just do not spawna even with the modifications the car. Modifications like color, neon, bumpers and etc are being saved yes. How can I solve this?

**Comment by LeoSHK** [comment]
@SirOficial Realizei um update no script, teste por favor.
